# Generated by Django 4.2.6 on 2023-10-09 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(unique=True, verbose_name='айди')),
                ('name', models.CharField(max_length=300, verbose_name='название')),
                ('category', models.CharField(max_length=100, verbose_name='категория')),
                ('activity_status', models.BooleanField(choices=[(True, 'активность есть'), (False, 'активности нет')], default=True, verbose_name='статус активности')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена')),
            ],
            options={
                'verbose_name': 'информация о товаре',
                'verbose_name_plural': 'информация о товарах',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_last_month', models.IntegerField(verbose_name='заказы за прошлый месяц')),
                ('order_with_first_day', models.IntegerField(verbose_name='заказы с 1 дня месяца')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='service.product', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'ordering': ['product'],
            },
        ),
    ]
